```{r}
library(pracma)

func=function(x, y){
  return (2*(2*x+3*y)/5)
}

result = integral2(func, 0, 1, 0, 1)       # lx, ux, ly, uy
print(result$Q)

marginal_gx_at_1 = integrate(function(y) func(1,y), 0, 1)
print(marginal_gx_at_1)

marginal_hy_at_0 = integrate(function(x) func(x,0), 0, 1)
print(marginal_hy_at_0)

expected_xy = integral2(function(x,y) x*y*func(x,y), 0, 1, 0, 1)
print(expected_xy$Q)
```

```{r}
func=function(x,y){
  return ((x+y)/30)
}
x=0:3
y=0:2
joint_pmf = outer(x, y, func)
print("joint pmf matrix:")
print(joint_pmf)

total_prob = sum(joint_pmf)
print("total probability:")
print(total_prob)

gx = apply(joint_pmf, 1, sum)
print(gx)

hy = apply(joint_pmf, 2, sum)
print(hy)

f_x0_y1 = joint_pmf[1,2]
p_y1 = hy[2]
cond_prob = f_x0_y1 / p_y1
print("conditional probab")
print(cond_prob)

Ex = sum(x*gx)
Ex2 = sum(x^2 * gx)
Varx = Ex2 - Ex^2
Ey = sum(y*hy)
Ey2 = sum(h^2 * hy)
Vary = Ey2 - Ey^2
Exy = sum(x*y*joint_pmf)
Covxy = Exy - Ex*Ey
Corr = Covxy / (sqrt(Varx) * sqrt(Vary))
```