```{r}
# loop
for (i in seq(1, 10, by = 2)) {
  print(i)
}

# Handling complex nums
c_num1 = 2 + 3i
c_num2 = 5 + 4i
c_num1 * c_num2
```
```{r}
# Vectors : apply() does not work on vectors. instead use sapply(x, function(val) dexp(val, lambda) )
a = 1:5
b = 5:1
a + b
a * 2
a^b         # exponent
a %% b      # remainder
```

```{r}
# Array
arr = array(1:24, dim=c(3,4,2))  # 3D
arr
print("Dimensions:")
dim(arr)

print("Row wise sum:")
apply(arr, 1, sum)

print("Layer wise mean:")
apply(arr,3,mean)

print("Collapse the 3rd dimension:")
apply(arr,c(1,2),sum)
```

```{r}
# Matrix
mat = matrix(1:9, nrow=3, ncol=3)
print(mat)
print("product of mat and transpose of mat:")
print(mat %*% t(mat))

print("35 is present in mat?")
35 %in% mat
print("Dimensions of mat:")
dim(mat)

print("# rows in mat:")
nrow(mat)

print("# cols in mat:")
ncol(mat)

print("# elements in mat:")
length(mat)

print("sum of each row in mat:")
rowSums(mat)

print("sum of each col in mat:")
colSums(mat)

print("mean of each row in mat:")
apply(mat,1,mean)

print("Accessing elements in matrix:")
print(mat[1,2])
```

```{r}
# Dataframes
df = data.frame(letters = c("a","b","c"), numbers = c("1","2","3"))
print(df)
```

```{r}
# Plotting
x = 1:3
y = seq(2,6,2)
plot(x, y, type = "p", col="red", main = "Scatter plot")
plot(x, y, type = "l", col="blue", main = "Line plot")
plot(x, y, type = "b", col="blue", main = "Both line and scatter plot")

values = seq(10,40,10)
names = c("A", "B", "C", "D")
barplot(values, names.arg = names, col = "red", main="Bar plot")
```

